### ISSUE TITLE
Stop making source modifications during build

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet#1010]
During the build several source files are modified.  E.g. NuGet feeds are injected, the SDK in the global.json is set to a common version, etc.  These didn't cause a problem within a tarball environment but now with the VMR, the present a usability issue for developers making changes intended to be submitted as these infra changes should not be committed.  

This PR is a tracking issue to address the following issues:

- [x] https://github.com/dotnet/source-build/issues/3170
- [ ] https://github.com/dotnet/dotnet/issues/1004
- [x] https://github.com/dotnet/source-build/issues/3117
- [x] https://github.com/dotnet/source-build/issues/3171
- [ ] dotnet/source-build#4038

**Comment by tkapin** [comment]
This is currently paused, might require additional product changers to not modify the global.json.
