### ISSUE TITLE
Unified Build Versioning

### ISSUE THREAD

**Issue by mmitche** [dotnet/dotnet#1044]
This epic covers versioning of assets generated by the VMR.

## Background

The VMR produces the same assets as the current Microsoft build. In .NET 9, the versions of these produced assets are defined by the version numbers that flow into the SDK from various components. The VMR sync process extracts the original official build id used to create those assets (e.g. 20240101.1 -> preview.1.1234.5), and those official build ids are fed into each repo build that comprises the VMR.

In .NET 10, that dependency flow ceases. All flow into the VMR is in parallel, and there are no official build ids that would be available for most components. At that point, the VMR will control the versioning of the output assets. This epic describes how to get from .NET 9 style versioning to full VMR versioning

## Work Items

- [x] dotnet/dotnet#1043
- [x] dotnet/source-build#4611
- [x] dotnet/source-build#4612
- [x] dotnet/source-build#4613
- [x] dotnet/source-build#4614
- [x] dotnet/source-build#4615 
- [x] https://github.com/dotnet/dotnet/issues/1053
- [x] https://github.com/dotnet/source-build/issues/4474

**Comment by mmitche** [comment]
Preview stable and full stable releases now work as expected. CLosing
